// export const PAGE_PATH = 'https://www.sapphirestudio.online';
export const PAGE_PATH = 'https://www.sapphirestudio.online';
export const API_PATH = 'https://test-83kl6hmmy-antonisabats-projects.vercel.app';
// export const API_PATH = 'http://localhost:3000';
export const GRAPHQL_API = "https://test-83kl6hmmy-antonisabats-projects.vercel.app/graphql";
// export const GRAPHQL_API = "http://localhost:3000/graphql";
export const CDN_API = 'https://api.imgbb.com/1/upload?key=ced1032cda8964de96c804e90ef55716';
export const KINDE_CLIENT_ID = "be6bc899d09248b8bf1d8c41feddb8ee";
export const KINDE_DOMAIN = "https://sapphirestudio.kinde.com";
export const KINDE_REDIRECT_URI = "https://www.sapphirestudio.online/";
// export const KINDE_REDIRECT_URI = "https://www.sapphirestudio.online";
export const KINDE_LOGOUT_URI = "https://www.sapphirestudio.online/";
// export const KINDE_LOGOUT_URI = "https://www.sapphirestudio.online";
